export default {
  points: [
    'More than 15 years of experience in web development and related fields.',
    'Solid JavaScript knowledge, both back-end (preferred) and front-end.',
    'Relational, NoSQL, and Document based database experience.',
    'Used plain-old-http, REST, WebSockets, and GraphQL to communicate with many diverse APIs.',
    'Have no problem learning new languages, libraries, frameworks, etc.',
    'Developed on-line, off-line, real-time, specialized, generalized, and mixed applications.',
    'Wrote code to generate PDFs, images, graphs, thumbnails, and code.',
    'Works primarily in Linux.',
  ],
  details: [
    {
      title: 'Tech Lead',
      employer: 'appsintegra',
      location: 'Abu Dhabi, United Arab Emirates',
      logo: '/img/logos/appsintegra.png',
      startDate: 'Nov 2018',
      endDate: 'Present',
      technologies: [
        'node.js',
        'typescript',
        'reactjs',
        'graphql',
        'git',
        'esb',
        'microservices',
        'unit testing',
        'scrum',
        'agile',
      ],
      description:
        'Leading a multi-cultural team of several developers and QAs, utilizing agile techniques and modern development practices, tools, and infrastructure to, in cooperation with other teams, deliver services linking government entities and end-users (TAMM Project).',
    },
    {
      title: 'Developer',
      employer: 'InertiaSystems ltd',
      location: 'remote',
      logo: '/img/logos/inertiasystems-ltd.png',
      startDate: 'Jun 2016',
      endDate: 'Feb 2017',
      technologies: [
        'node.js',
        'autodesk-forge',
        'mongodb',
        'reactjs',
        'vue.js',
        'express',
        'git',
      ],
      description:
        'Creating the backend to manage, and convert Autodesk files to an intermediate format that the next layer of 2D and 3D viewers can load and show online. Extracting and organizing metadata of those files. Integrating viewer code with the infrastructure. Creating realtime chat and changes backend.',
    },
    {
      title: 'VP of Engineering',
      employer: 'Loyalis',
      location: 'Belgrade, Serbia',
      logo: '/img/logos/loyalis.png',
      startDate: 'Jul 2015',
      endDate: 'Mar 2016',
      technologies: ['node.js', 'mongodb', 'express', 'angularjs', 'git'],
      description:
        'Keeping the existing app working, optimizing existing processes (including rewrites), implementing new functionality, and general server maintenance.',
    },
    {
      title: 'External developer',
      employer: 'designessentials',
      location: 'remote',
      logo: '/img/logos/designessentials.png',
      startDate: 'May 2014',
      endDate: 'Jun 2015',
      technologies: ['php', 'html', 'css', 'javascript', 'mysql', 'cms', 'git'],
      description: 'Development of several websites and CMSs for the agency.',
    },
    {
      title: 'Primary developer',
      employer: 'pixelimage',
      location: 'Basel, Switzerland',
      logo: '/img/logos/pixelimage.png',
      startDate: 'Sep 2014',
      endDate: 'Nov 2014',
      technologies: ['php', 'cordova', 'mysql', 'phonegap-build', 'git'],
      description:
        'Complete development of a CMS for mobile apps. The user could create a (simple) app online, fill it with content and compile it for publish in the stores. After publishing, app could be updated almost in realtime, without need for republishing.',
    },
    {
      title: 'Lead Developer',
      employer: 'mediaONE Agency',
      location: 'Belgrade, Serbia',
      logo: '/img/logos/mediaone-agency.png',
      startDate: 'Mar 2012',
      endDate: 'Jun 2013',
      technologies: [
        'php',
        'cakephp',
        'mysql',
        'jquery',
        'video',
        'mobile',
        'zencoder',
        'git',
      ],
      description:
        'Many different projects (mostly websites with CMS, but also a few mobile apps), complete development.',
    },
    {
      title: 'Senior Software Developer',
      employer: 'HALO Creative Agency',
      location: 'Belgrade, Serbia',
      logo: '/img/logos/haloagency.png',
      startDate: 'Jul 2009',
      endDate: 'Mar 2012',
      technologies: [
        'php',
        'cakephp',
        'amfphp',
        'jquery',
        'mysql',
        'postgresql',
        'api',
        'cms',
        'git',
      ],
      description:
        'Complete development of custom CMS solutions for a diverse list of clients.',
    },
    {
      title: 'Programmer',
      employer: 'Maccom Media',
      location: 'Belgrade, Serbia',
      logo: '/img/logos/maccommedia.png',
      startDate: 'Apr 2006',
      endDate: 'Apr 2007',
      technologies: ['php', 'javascript', 'jquery', 'cakephp', 'sql', 'cms'],
      description:
        'Complete development of custom CMS solutions for a diverse list of clients.',
    },
    {
      title: 'Programmer',
      employer: 'Cactimedia',
      location: 'remote',
      logo: '/img/logos/cactimedia.png',
      startDate: 'Sep 2005',
      endDate: 'Feb 2006',
      technologies: ['php', 'javascript', 'sql', 'cms'],
      description:
        'Complete development of custom CMS solutions for a diverse list of clients.',
    },
  ],
}
